name: Python Tests

on: [ push, workflow_dispatch ]

env:
  BASE_URL_API: ${{secrets.BASE_URL_API}}
  KAFKA_PRODUCER: ${{secrets.KAFKA_PRODUCER}}
  RMQ_PUBLISHER_URL: ${{secrets.RMQ_PUBLISHER_URL}}

jobs:
  test:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: pip install poetry

      - uses: actions/cache@v5
        with:
          path: ~/.cache/pypoetry
          key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Configure Poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run tests
        run: pytest framework/tests
        continue-on-error: true
