name: Python Tests

on:
  - push
  - pull_request

env:
  BASE_URL_API: ${{secrets.BASE_URL_API}}
  KAFKA_PRODUCER: ${{secrets.KAFKA_PRODUCER}}

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: "poetry"

      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run tests
        run: |
          pytest ./tests --alluredir=allure-results --disable-warnings
        continue-on-error: true

      - name: Archive allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1